### ISSUE TITLE
tensorflow 2.1.0에서 2.2이상부터 GPU계산 성능이 떨어지는 이유는 뭔가요?

### ISSUE THREAD

**Issue by huniel** [codingeverybody/codingyahac#1051]
안녕하세요.
작년에 사용하던 tensflow 2.1.0을 사용하다가 최근데 tensorflow2.4.0으로 업그레이드 했습니다.
그런데 문제는 tensforflow 2.1.0보다 처리 성능이 많이 떨어진다는 것입니다.
그리고 GPU사용일때가 CPU만 사용할때 보다 훨씬 느립니다.
왜 그런지 아시는 분 계신가요?

# 해결하고자 하는 문제

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
windows10에서 python+ vscode 사용

# 시도해본 방법

**Comment by jeuxdeau** [comment]
어떤 작업을 하고 계신지, 또는 어떤 환경에서 작업하고 계신지에 따라 정말 다양한 이유가 있을 것 같은데요, 비슷한 질문 링크 몇 개를 찾아보았습니다.

- [Tensorflow gpu vs cpu 속도](https://www.facebook.com/groups/TensorFlowKR/permalink/494563400884723/) (한국어, 코멘트 란에 여러 가지 추측이나 설명이 있는데, 이 중에서 한 가지 이유를 찾아볼 수 있을까요?)
- [Training a simple model in Tensorflow GPU slower than CPU](https://stackoverflow.com/questions/55749899/training-a-simple-model-in-tensorflow-gpu-slower-than-cpu) (영어, 작은 행렬을 계산할 때는 실제 계산에 쓰는 시간보다 부차적인 시간(예: 데이터를 복사하는 데 걸리는 시간)이 큰 비중을 차지한다는 내용입니다.)
- [Why are we still using CPUs instead of GPUs?
](https://superuser.com/questions/308771/why-are-we-still-using-cpus-instead-of-gpus) (영어, 이 질문과는 직접적인 연관이 없을 수도 있지만... CPU와 GPU는 각기 다른 목적을 가지고 설계되었고, 특정 작업에는 GPU가 빠르고 다른 작업에는 CPU가 빠를 수 있다는 답변입니다. "더 빠르고 효율이 좋은 보잉 747이 있는데 왜 자동차를 타고 다니죠?" 라는 댓글이 너무 재미있네요. ㅎㅎ)

또 텐서플로우의 특정 버전이나 코드에 문제가 있는 것 같다 싶으시면, [텐서플로우 repo의 issue](https://github.com/tensorflow/tensorflow/issues)에서 비슷한 글을 찾아보시거나 새로운 이슈를 리포트하시는 방법도 있습니다. 여기까지 정말 두루뭉술한 답변이었는데요... 도움이 되었으면 좋겠습니다.

**Comment by huniel** [comment]
답변감사합니다.
tensorflow 101강의에서 나왔던 swish 액티베이션 함수 사용했던, 보스턴집값 예측 예제프로그램입니다.


2021년 1월 4일 (월) 오후 4:10, Woobin Park <notifications@github.com>님이 작성:

**Comment by YoungHaKim7** [comment]
https://coding-groot.tistory.com/87
 cuda 버젼을 맞춰서 해 보셨나요?
 해당 그래픽 마다 버젼이 다른것 같습니다.

**Comment by hephaex** [comment]
사용하시는 GPU가 Nvidia 사 제품이라면 CUDA 버전을 확인해 보세요. Tensorflow 2.4는 CUDA 11.0을 지원합니다. 
이전 CUDA 버전을 사용하신다면 GPU가 아닌 CPU로 작동할 수 있습니다. CPU로 동작한다면 당연히 성능이 잘 나오지 않겠죠. 
설치된 CUDA 버전을 확인해 보세요.

**Comment by huniel** [comment]
> 사용하시는 GPU가 Nvidia 사 제품이라면 CUDA 버전을 확인해 보세요. Tensorflow 2.4는 CUDA 11.0을 지원합니다.
> 이전 CUDA 버전을 사용하신다면 GPU가 아닌 CPU로 작동할 수 있습니다. CPU로 동작한다면 당연히 성능이 잘 나오지 않겠죠.
> 설치된 CUDA 버전을 확인해 보세요.

https://blog.naver.com/spinglass/222194630599
여기 블로그 제가 올린겁니다.
이걸로 설치했습니다.

**Comment by huniel** [comment]
> 어떤 작업을 하고 계신지, 또는 어떤 환경에서 작업하고 계신지에 따라 정말 다양한 이유가 있을 것 같은데요, 비슷한 질문 링크 몇 개를 찾아보았습니다.
> 
> * [Tensorflow gpu vs cpu 속도](https://www.facebook.com/groups/TensorFlowKR/permalink/494563400884723/) (한국어, 코멘트 란에 여러 가지 추측이나 설명이 있는데, 이 중에서 한 가지 이유를 찾아볼 수 있을까요?)
> * [Training a simple model in Tensorflow GPU slower than CPU](https://stackoverflow.com/questions/55749899/training-a-simple-model-in-tensorflow-gpu-slower-than-cpu) (영어, 작은 행렬을 계산할 때는 실제 계산에 쓰는 시간보다 부차적인 시간(예: 데이터를 복사하는 데 걸리는 시간)이 큰 비중을 차지한다는 내용입니다.)
> * [Why are we still using CPUs instead of GPUs?
>   ](https://superuser.com/questions/308771/why-are-we-still-using-cpus-instead-of-gpus) (영어, 이 질문과는 직접적인 연관이 없을 수도 있지만... CPU와 GPU는 각기 다른 목적을 가지고 설계되었고, 특정 작업에는 GPU가 빠르고 다른 작업에는 CPU가 빠를 수 있다는 답변입니다. "더 빠르고 효율이 좋은 보잉 747이 있는데 왜 자동차를 타고 다니죠?" 라는 댓글이 너무 재미있네요. ㅎㅎ)
> 
> 또 텐서플로우의 특정 버전이나 코드에 문제가 있는 것 같다 싶으시면, [텐서플로우 repo의 issue](https://github.com/tensorflow/tensorflow/issues)에서 비슷한 글을 찾아보시거나 새로운 이슈를 리포트하시는 방법도 있습니다. 여기까지 정말 두루뭉술한 답변이었는데요... 도움이 되었으면 좋겠습니다.

올려주신 내용이 맞다면 좀 더 테스트해 봐야 할것 같네요.
중요한 내용 알려주셔서 감사합니다.

**Comment by huniel** [comment]
> https://coding-groot.tistory.com/87
> cuda 버젼을 맞춰서 해 보셨나요?
> 해당 그래픽 마다 버젼이 다른것 같습니다.

아래 제가 올린 블로그처럼  현재 최신버전 조합으로 세팅했습니다.
https://blog.naver.com/spinglass/222194630599

**Comment by huniel** [comment]
> > 어떤 작업을 하고 계신지, 또는 어떤 환경에서 작업하고 계신지에 따라 정말 다양한 이유가 있을 것 같은데요, 비슷한 질문 링크 몇 개를 찾아보았습니다.
> > 
> > * [Tensorflow gpu vs cpu 속도](https://www.facebook.com/groups/TensorFlowKR/permalink/494563400884723/) (한국어, 코멘트 란에 여러 가지 추측이나 설명이 있는데, 이 중에서 한 가지 이유를 찾아볼 수 있을까요?)
> > * [Training a simple model in Tensorflow GPU slower than CPU](https://stackoverflow.com/questions/55749899/training-a-simple-model-in-tensorflow-gpu-slower-than-cpu) (영어, 작은 행렬을 계산할 때는 실제 계산에 쓰는 시간보다 부차적인 시간(예: 데이터를 복사하는 데 걸리는 시간)이 큰 비중을 차지한다는 내용입니다.)
> > * [Why are we still using CPUs instead of GPUs?
> >   ](https://superuser.com/questions/308771/why-are-we-still-using-cpus-instead-of-gpus) (영어, 이 질문과는 직접적인 연관이 없을 수도 있지만... CPU와 GPU는 각기 다른 목적을 가지고 설계되었고, 특정 작업에는 GPU가 빠르고 다른 작업에는 CPU가 빠를 수 있다는 답변입니다. "더 빠르고 효율이 좋은 보잉 747이 있는데 왜 자동차를 타고 다니죠?" 라는 댓글이 너무 재미있네요. ㅎㅎ)
> > 
> > 또 텐서플로우의 특정 버전이나 코드에 문제가 있는 것 같다 싶으시면, [텐서플로우 repo의 issue](https://github.com/tensorflow/tensorflow/issues)에서 비슷한 글을 찾아보시거나 새로운 이슈를 리포트하시는 방법도 있습니다. 여기까지 정말 두루뭉술한 답변이었는데요... 도움이 되었으면 좋겠습니다.
> 
> 올려주신 내용이 맞다면 좀 더 테스트해 봐야 할것 같네요.
> 중요한 내용 알려주셔서 감사합니다.

테스트해 보니 보스턴집값예측(swish함수사용) 같은 간단한 모델은 GPU 사용이 CPU만 사용한 경우보다 10배 느리네요.
